### ISSUE TITLE
Quotes need to be stripped from options when rendering the RecaptchaField

### ISSUE THREAD

**Issue by zanderwar** [chillu/silverstripe-recaptcha#48]
v: dev-master

```yml
SilverStripe\Recaptcha\RecaptchaField:
  options:
    size: compact
    type: audio
```

results in:

```html
<div class="g-recaptcha" id="Captcha" data-sitekey="xxxxxx" data-size="&quot;compact&quot;" data-type="&quot;audio&quot;">
```
